// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/_middleware.ts";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/api/locale/[locale].ts";
import * as $4 from "./routes/index.tsx";
import * as $$0 from "./islands/Construction.tsx";
import * as $$1 from "./islands/Counter.tsx";
import * as $$2 from "./islands/Illustration.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/_middleware.ts": $1,
    "./routes/api/joke.ts": $2,
    "./routes/api/locale/[locale].ts": $3,
    "./routes/index.tsx": $4,
  },
  islands: {
    "./islands/Construction.tsx": $$0,
    "./islands/Counter.tsx": $$1,
    "./islands/Illustration.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
